from enum import Enum

class ErrorCode(str, Enum):
    # Authentication Errors
    AUTH_INVALID_CREDENTIALS = "AUTH001"
    AUTH_ACCOUNT_LOCKED = "AUTH002"
    AUTH_CAPTCHA_INVALID = "AUTH003"
    AUTH_TOKEN_EXPIRED = "AUTH004"
    AUTH_UNAUTHORIZED = "AUTH005"
    AUTH_INACTIVE_ACCOUNT = "AUTH006"
    AUTH_UNVERIFIED_EMAIL = "AUTH007"
    AUTH_INVALID_TOKEN = "AUTH008"
    AUTH_PASSWORD_REUSED = "AUTH009"
    AUTH_TOKEN_ROTATION_FAILED = "AUTH010"

    # Registration Errors
    REG_USERNAME_EXISTS = "REG001"
    REG_EMAIL_EXISTS = "REG002"
    REG_INVALID_PASSWORD = "REG003"
    REG_INVALID_DATA = "REG004"
    REG_DISPOSABLE_EMAIL = "REG005"
    REG_WEAK_PASSWORD = "REG006"

    # Global Errors
    INTERNAL_SERVER_ERROR = "GLB001"
    VALIDATION_ERROR = "GLB002"
    NOT_FOUND = "GLB003"
    GLB_RATE_LIMIT = "GLB004"
    
    # Payload / DoS Protection Errors
    PAYLOAD_TOO_LARGE = "DOS001"
    PAYLOAD_DEPTH_EXCEEDED = "DOS002"
    PAYLOAD_MALFORMED = "DOS003"
    PAYLOAD_COMPRESSION_BOMB = "DOS004"
    MULTIPART_TOO_MANY_PARTS = "DOS005"

    # Workflow / Business Logic Errors
    WFK_INVALID_STATE = "WFK001"
    WFK_SESSION_NOT_FOUND = "WFK002"
    WFK_SESSION_EXPIRED = "WFK003"
    WFK_ATTEMPT_LIMIT_REACHED = "WFK004"
    WFK_ACCESS_DENIED = "WFK005"
    WFK_REPLAY_ATTACK = "WFK006"
