# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import sentiment_pb2 as protos_dot_sentiment__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/sentiment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SentimentAnalysisStub(object):
    """Service definition for AI Sentiment Analysis
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSentiment = channel.unary_unary(
                '/sentiment.SentimentAnalysis/AnalyzeSentiment',
                request_serializer=protos_dot_sentiment__pb2.AnalyzeSentimentRequest.SerializeToString,
                response_deserializer=protos_dot_sentiment__pb2.AnalyzeSentimentResponse.FromString,
                _registered_method=True)
        self.StreamSentiment = channel.stream_stream(
                '/sentiment.SentimentAnalysis/StreamSentiment',
                request_serializer=protos_dot_sentiment__pb2.AnalyzeSentimentRequest.SerializeToString,
                response_deserializer=protos_dot_sentiment__pb2.AnalyzeSentimentResponse.FromString,
                _registered_method=True)


class SentimentAnalysisServicer(object):
    """Service definition for AI Sentiment Analysis
    """

    def AnalyzeSentiment(self, request, context):
        """Analyzes a single piece of text for sentiment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSentiment(self, request_iterator, context):
        """Streaming version for large journal entries or batch processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentimentAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=protos_dot_sentiment__pb2.AnalyzeSentimentRequest.FromString,
                    response_serializer=protos_dot_sentiment__pb2.AnalyzeSentimentResponse.SerializeToString,
            ),
            'StreamSentiment': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSentiment,
                    request_deserializer=protos_dot_sentiment__pb2.AnalyzeSentimentRequest.FromString,
                    response_serializer=protos_dot_sentiment__pb2.AnalyzeSentimentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentiment.SentimentAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentiment.SentimentAnalysis', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SentimentAnalysis(object):
    """Service definition for AI Sentiment Analysis
    """

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentiment.SentimentAnalysis/AnalyzeSentiment',
            protos_dot_sentiment__pb2.AnalyzeSentimentRequest.SerializeToString,
            protos_dot_sentiment__pb2.AnalyzeSentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSentiment(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sentiment.SentimentAnalysis/StreamSentiment',
            protos_dot_sentiment__pb2.AnalyzeSentimentRequest.SerializeToString,
            protos_dot_sentiment__pb2.AnalyzeSentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
