# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/sentiment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/sentiment.proto\x12\tsentiment\"L\n\x17\x41nalyzeSentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\njournal_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"^\n\x18\x41nalyzeSentimentResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x12\r\n\x05label\x18\x02 \x01(\t\x12\x10\n\x08patterns\x18\x03 \x03(\t\x12\x12\n\njournal_id\x18\x04 \x01(\t2\xd4\x01\n\x11SentimentAnalysis\x12]\n\x10\x41nalyzeSentiment\x12\".sentiment.AnalyzeSentimentRequest\x1a#.sentiment.AnalyzeSentimentResponse\"\x00\x12`\n\x0fStreamSentiment\x12\".sentiment.AnalyzeSentimentRequest\x1a#.sentiment.AnalyzeSentimentResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZESENTIMENTREQUEST']._serialized_start=37
  _globals['_ANALYZESENTIMENTREQUEST']._serialized_end=113
  _globals['_ANALYZESENTIMENTRESPONSE']._serialized_start=115
  _globals['_ANALYZESENTIMENTRESPONSE']._serialized_end=209
  _globals['_SENTIMENTANALYSIS']._serialized_start=212
  _globals['_SENTIMENTANALYSIS']._serialized_end=424
# @@protoc_insertion_point(module_scope)
